# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: this_is_cleverson
author: Cleverson Silva
email: cleverson.silva.contact@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Apenas um latino-americano tentando falar sobre este vasto mundo da tecnologia e a complexa vida...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thisiscleverson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/img/happy-computer.ico

permalink: /blog/:year-:month-:day/:title
excerpt_separator: <!--more-->
timezone: America/Sao_Paulo


paginate: 10
paginate_path: "/blog/page:num/"


sass:
  style: compact


collections:
  tag:
    output: true


defaults:
  -
    scope:
      path: ""
      type: tag
    values:
      layout: "tags"


# Build settings
markdown: kramdown
plugins:
  - jekyll-katex
  
